# Generated by Django 5.0.3 on 2024-03-31 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kitob_beti', models.IntegerField()),
                ('aftor', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='kitob_image')),
                ('kitob_tili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tillar', to='kitoblar.tillar')),
            ],
        ),
    ]
